### ISSUE TITLE
Engine crashes when AI tries to checkmate

### ISSUE THREAD

**Issue by ElwynJohn** [rleathart/ChessEngine#15]
This might be because the iterative deepening commit may have broken the checkmating code in the "search" function.

Starting fen:
k7/8/8/8/8/6qp/8/K7 w - 0 1

[chess.log](https://github.com/rleathart/ChessEngine/files/6911456/chess.log)

**Comment by rleathart** [comment]
Pretty sure this is because we are accessing free'd memory in the tree. Guess we need to find a way of storing the checkmate line information while still freeing what we don't need?
