### ISSUE TITLE
Moving bishop crash

### ISSUE THREAD

**Issue by rleathart** [rleathart/ChessEngine#7]
Engine crashes here when moving bishop from d3 to c4

![image](https://user-images.githubusercontent.com/56587304/125206409-0d7dbc00-e27f-11eb-8c25-352e9aadcc36.png)

**Comment by ElwynJohn** [comment]
`c
  if (nmoves == 0) // Either checkmate or stalemate
  {
    if (!is_in_check(board, maximising_player)) // Stalemate
      best_eval = 0;

    //goto end without initialising best_eval_i may be causing the crash
    goto end;
  }

  if (depth == 0)
  {
    best_eval = evaluate_board(board);
    goto end;
  }
`

goto end without initialising best_eval_i might be causing this. or maybe a different initialisation error

**Comment by ElwynJohn** [comment]
```c
  if (nmoves == 0) // Either checkmate or stalemate
  {
    if (!is_in_check(board, maximising_player)) // Stalemate
      best_eval = 0;

    goto end;
  }

  if (depth == 0)
  {
    best_eval = evaluate_board(board);
    goto end;
  }
```
goto end without initialising best_eval_i may be causing the crash
